[package]
edition = "2021"
name = "ecg"
version = "0.1.0"

authors = ["Etienne Napoleone <etienne@setten.io>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
serde-aux = "3.0"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.clap]
features = ["derive", "env"]
version = "3.1"

[dependencies.ureq]
features = ["json"]
version = "2.4"
