[package]
edition = "2021"
name = "ecg"
version = "0.1.0"

authors = ["Etienne Napoleone <etienne@setten.io>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
ureq = "2.4"

[dependencies.clap]
features = ["derive", "env"]
version = "3.1"
